working_dir:
    "/hps/nobackup/birney/users/ian/hmn_fst"
traits:
contigs:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
gz_exts:
    - ".gz"
    - ".gz.tbi"
#ftp_dir_1kg_37:
#    "ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20130502"
#ftp_dir_1kg_38:
#    "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000_genomes_project/release/20190312_biallelic_SNV_and_INDEL"
#ftp_dbsnp_vcf:
#    "https://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/00-All.vcf"
log_dir:
    "/hps/nobackup/birney/users/ian/hmn_fst/log"
ftp_dir_1kg_38_annotated:
    "ftp://ftp.ensembl.org/pub/data_files/homo_sapiens/GRCh38/variation_genotype"
new_header:
    "data/1kg/20150319/new_header.vcf"
date_of_gwas_collection:
    "20210525"
date_of_dbsnp_collection:
    "20210524"
tmp_dir:
    "/hps/nobackup/birney/users/ian/hmn_fst/tmp"
picard:
    "/hps/software/users/birney/ian/containers/picard_2.25.2.sif"
r-base:
    "/hps/software/users/birney/ian/containers/r-base_4.0.5.sif"
bcftools:
    "/hps/software/users/birney/ian/containers/bcftools_1.9.sif"
plink1.9:
    "/hps/software/users/birney/ian/containers/plink_1.9_1.90b6.6.sif"
rscript:
    "Rscript --no-save --no-restore --no-environ --no-site-file"
ftp_pop_file:
    "ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/working/20130606_sample_info/20130606_sample_info.xlsx"
local_pop_file:
    "data/1kg_populations.csv"
local_pop_file_plink:
    "data/1kg_populations_plink.txt"
get_fst_script:
    "code/scripts/get_fst.R"
get_associations_script:
    "code/scripts/get_associations.R"
get_variants_script:
    "code/scripts/get_variants.R"
#####################
# Variables
#####################
clump_r2:
    "0.1"
clump_kb:
    "1000"

