#####################
# Locations
#####################
working_dir:
    /hps/nobackup/birney/users/ian/hmn_fst
lts_dir:
    /nfs/research/birney/users/ian/hmn_fst
log_dir:
    /hps/nobackup/birney/users/ian/hmn_fst/logs
tmp_dir:
    /hps/nobackup/birney/users/ian/hmn_fst/tmp
#####################
# Variables
#####################
#trait_ids_file:
#    code/snakemake/20210625/config/trait_ids.tsv
#additional_traits:
#    - COVID-19
contigs:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
gz_exts:
    - .gz
    - .gz.tbi
date_of_gwas_collection:
    20210809
clump_r2:
    0.1
clump_kb:
    1000
# EFO ID for body height
ref_efo_id:
    EFO_0004339
# Percentile bin range to gather control SNPs
percent_interval:
    5
#####################
# Containers
#####################
picard:
    docker://quay.io/biocontainers/picard:2.9.2--2
bash:
    docker://bash:5.1.8
R:
    /hps/nobackup/birney/users/ian/containers/human_traits_fst/R_4.1.0.sif
bcftools:
    docker://quay.io/biocontainers/bcftools:1.10--h5d15f04_0
plink1.9:
    docker://biocontainers/plink1.9:v1.90b6.6-181012-1-deb_cv1
julia:
    docker://julia:1.6.2
snpsift:
    docker://quay.io/biocontainers/snpsift:4.3.1t--2
#####################
# Key files
#####################
all_trait_ids_file:
    code/snakemake/20210625/config/20210809_all_traits.tsv
filt_trait_ids_file:
    code/snakemake/20210625/config/20210809_filtered_traits.txt
ftp_dir_1kg_38_annotated:
    ftp://ftp.ensembl.org/pub/data_files/homo_sapiens/GRCh38/variation_genotype
ftp_dir_1kg_38_highcov:
    ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/data_collections/1000G_2504_high_coverage/working/20201028_3202_phased
dbsnp_vcf_prefix:
    ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606/VCF/00-All.vcf
1kgp_2504_samples:
    code/snakemake/20210625/config/1kgp_2504_samples.txt
#new_header:
#    data/1kg/20150319/new_header.vcf
ftp_pop_file:
    https://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/working/20130606_sample_info/20130606_sample_info.xlsx
local_pop_file:
    data/1kg_populations.csv
local_pop_file_plink:
    data/1kg_populations_plink.txt




